#pragma once

#include "il2cpp-config.h"

#ifndef _MSC_VER
# include <alloca.h>
#else
# include <malloc.h>
#endif

#include <stdint.h>
#include <assert.h>
#include <exception>

// OpenCVForUnity.Ccalib
struct Ccalib_t3187470999;
// OpenCVForUnity.Mat
struct Mat_t1174969555;
// OpenCVForUnity.Size
struct Size_t1177469876;
// System.Collections.Generic.List`1<OpenCVForUnity.Mat>
struct List_1_t1971928524;
// OpenCVForUnity.TermCriteria
struct TermCriteria_t3969392542;
// OpenCVForUnity.MatOfPoint3f
struct MatOfPoint3f_t580066431;
// OpenCVForUnity.MatOfPoint2f
struct MatOfPoint2f_t580066400;

#include "codegen/il2cpp-codegen.h"
#include "AssemblyU2DCSharp_OpenCVForUnity_Mat1174969555.h"
#include "AssemblyU2DCSharp_OpenCVForUnity_Size1177469876.h"
#include "AssemblyU2DCSharp_OpenCVForUnity_TermCriteria3969392542.h"
#include "AssemblyU2DCSharp_OpenCVForUnity_MatOfPoint3f580066431.h"
#include "AssemblyU2DCSharp_OpenCVForUnity_MatOfPoint2f580066400.h"
#include "mscorlib_System_IntPtr676692020.h"

// System.Void OpenCVForUnity.Ccalib::.ctor()
extern "C"  void Ccalib__ctor_m3960135330 (Ccalib_t3187470999 * __this, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::calibrate(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Size,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Int32,OpenCVForUnity.TermCriteria,OpenCVForUnity.Mat)
extern "C"  double Ccalib_calibrate_m536803599 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___objectPoints, Mat_t1174969555 * ___imagePoints, Size_t1177469876 * ___size, Mat_t1174969555 * ___K, Mat_t1174969555 * ___xi, Mat_t1174969555 * ___D, List_1_t1971928524 * ___rvecs, List_1_t1971928524 * ___tvecs, int32_t ___flags, TermCriteria_t3969392542 * ___criteria, Mat_t1174969555 * ___idx, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::calibrate(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Size,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Int32,OpenCVForUnity.TermCriteria)
extern "C"  double Ccalib_calibrate_m550120092 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___objectPoints, Mat_t1174969555 * ___imagePoints, Size_t1177469876 * ___size, Mat_t1174969555 * ___K, Mat_t1174969555 * ___xi, Mat_t1174969555 * ___D, List_1_t1971928524 * ___rvecs, List_1_t1971928524 * ___tvecs, int32_t ___flags, TermCriteria_t3969392542 * ___criteria, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::stereoCalibrate(System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,OpenCVForUnity.Size,OpenCVForUnity.Size,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Int32,OpenCVForUnity.TermCriteria,OpenCVForUnity.Mat)
extern "C"  double Ccalib_stereoCalibrate_m1995364827 (Il2CppObject * __this /* static, unused */, List_1_t1971928524 * ___objectPoints, List_1_t1971928524 * ___imagePoints1, List_1_t1971928524 * ___imagePoints2, Size_t1177469876 * ___imageSize1, Size_t1177469876 * ___imageSize2, Mat_t1174969555 * ___K1, Mat_t1174969555 * ___xi1, Mat_t1174969555 * ___D1, Mat_t1174969555 * ___K2, Mat_t1174969555 * ___xi2, Mat_t1174969555 * ___D2, Mat_t1174969555 * ___rvec, Mat_t1174969555 * ___tvec, List_1_t1971928524 * ___rvecsL, List_1_t1971928524 * ___tvecsL, int32_t ___flags, TermCriteria_t3969392542 * ___criteria, Mat_t1174969555 * ___idx, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::stereoCalibrate(System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,OpenCVForUnity.Size,OpenCVForUnity.Size,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Collections.Generic.List`1<OpenCVForUnity.Mat>,System.Int32,OpenCVForUnity.TermCriteria)
extern "C"  double Ccalib_stereoCalibrate_m3499803984 (Il2CppObject * __this /* static, unused */, List_1_t1971928524 * ___objectPoints, List_1_t1971928524 * ___imagePoints1, List_1_t1971928524 * ___imagePoints2, Size_t1177469876 * ___imageSize1, Size_t1177469876 * ___imageSize2, Mat_t1174969555 * ___K1, Mat_t1174969555 * ___xi1, Mat_t1174969555 * ___D1, Mat_t1174969555 * ___K2, Mat_t1174969555 * ___xi2, Mat_t1174969555 * ___D2, Mat_t1174969555 * ___rvec, Mat_t1174969555 * ___tvec, List_1_t1971928524 * ___rvecsL, List_1_t1971928524 * ___tvecsL, int32_t ___flags, TermCriteria_t3969392542 * ___criteria, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::initUndistortRectifyMap(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Size,System.Int32,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32)
extern "C"  void Ccalib_initUndistortRectifyMap_m4284924177 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___K, Mat_t1174969555 * ___D, Mat_t1174969555 * ___xi, Mat_t1174969555 * ___R, Mat_t1174969555 * ___P, Size_t1177469876 * ___size, int32_t ___mltype, Mat_t1174969555 * ___map1, Mat_t1174969555 * ___map2, int32_t ___flags, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::projectPoints(OpenCVForUnity.MatOfPoint3f,OpenCVForUnity.MatOfPoint2f,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Double,OpenCVForUnity.Mat,OpenCVForUnity.Mat)
extern "C"  void Ccalib_projectPoints_m568332232 (Il2CppObject * __this /* static, unused */, MatOfPoint3f_t580066431 * ___objectPoints, MatOfPoint2f_t580066400 * ___imagePoints, Mat_t1174969555 * ___rvec, Mat_t1174969555 * ___tvec, Mat_t1174969555 * ___K, double ___xi, Mat_t1174969555 * ___D, Mat_t1174969555 * ___jacobian, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::projectPoints(OpenCVForUnity.MatOfPoint3f,OpenCVForUnity.MatOfPoint2f,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Double,OpenCVForUnity.Mat)
extern "C"  void Ccalib_projectPoints_m2426201219 (Il2CppObject * __this /* static, unused */, MatOfPoint3f_t580066431 * ___objectPoints, MatOfPoint2f_t580066400 * ___imagePoints, Mat_t1174969555 * ___rvec, Mat_t1174969555 * ___tvec, Mat_t1174969555 * ___K, double ___xi, Mat_t1174969555 * ___D, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::stereoReconstruct(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32,System.Int32,System.Int32,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Size,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32)
extern "C"  void Ccalib_stereoReconstruct_m4281481475 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___image1, Mat_t1174969555 * ___image2, Mat_t1174969555 * ___K1, Mat_t1174969555 * ___D1, Mat_t1174969555 * ___xi1, Mat_t1174969555 * ___K2, Mat_t1174969555 * ___D2, Mat_t1174969555 * ___xi2, Mat_t1174969555 * ___R, Mat_t1174969555 * ___T, int32_t ___flag, int32_t ___numDisparities, int32_t ___SADWindowSize, Mat_t1174969555 * ___disparity, Mat_t1174969555 * ___image1Rec, Mat_t1174969555 * ___image2Rec, Size_t1177469876 * ___newSize, Mat_t1174969555 * ___Knew, Mat_t1174969555 * ___pointCloud, int32_t ___pointType, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::stereoReconstruct(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32,System.Int32,System.Int32,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat)
extern "C"  void Ccalib_stereoReconstruct_m3128267278 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___image1, Mat_t1174969555 * ___image2, Mat_t1174969555 * ___K1, Mat_t1174969555 * ___D1, Mat_t1174969555 * ___xi1, Mat_t1174969555 * ___K2, Mat_t1174969555 * ___D2, Mat_t1174969555 * ___xi2, Mat_t1174969555 * ___R, Mat_t1174969555 * ___T, int32_t ___flag, int32_t ___numDisparities, int32_t ___SADWindowSize, Mat_t1174969555 * ___disparity, Mat_t1174969555 * ___image1Rec, Mat_t1174969555 * ___image2Rec, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::stereoRectify(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat)
extern "C"  void Ccalib_stereoRectify_m54990886 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___R, Mat_t1174969555 * ___T, Mat_t1174969555 * ___R1, Mat_t1174969555 * ___R2, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::undistortImage(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32,OpenCVForUnity.Mat,OpenCVForUnity.Size,OpenCVForUnity.Mat)
extern "C"  void Ccalib_undistortImage_m834132929 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___distorted, Mat_t1174969555 * ___undistorted, Mat_t1174969555 * ___K, Mat_t1174969555 * ___D, Mat_t1174969555 * ___xi, int32_t ___flags, Mat_t1174969555 * ___Knew, Size_t1177469876 * ___new_size, Mat_t1174969555 * ___R, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::undistortImage(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,System.Int32)
extern "C"  void Ccalib_undistortImage_m940932295 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___distorted, Mat_t1174969555 * ___undistorted, Mat_t1174969555 * ___K, Mat_t1174969555 * ___D, Mat_t1174969555 * ___xi, int32_t ___flags, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::undistortPoints(OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat,OpenCVForUnity.Mat)
extern "C"  void Ccalib_undistortPoints_m1497729169 (Il2CppObject * __this /* static, unused */, Mat_t1174969555 * ___distorted, Mat_t1174969555 * ___undistorted, Mat_t1174969555 * ___K, Mat_t1174969555 * ___D, Mat_t1174969555 * ___xi, Mat_t1174969555 * ___R, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::ccalib_Ccalib_calibrate_10(System.IntPtr,System.IntPtr,System.Double,System.Double,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Double,System.IntPtr)
extern "C"  double Ccalib_ccalib_Ccalib_calibrate_10_m936664439 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_nativeObj, IntPtr_t ___imagePoints_nativeObj, double ___size_width, double ___size_height, IntPtr_t ___K_nativeObj, IntPtr_t ___xi_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___rvecs_mat_nativeObj, IntPtr_t ___tvecs_mat_nativeObj, int32_t ___flags, int32_t ___criteria_type, int32_t ___criteria_maxCount, double ___criteria_epsilon, IntPtr_t ___idx_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::ccalib_Ccalib_calibrate_11(System.IntPtr,System.IntPtr,System.Double,System.Double,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Double)
extern "C"  double Ccalib_ccalib_Ccalib_calibrate_11_m789409066 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_nativeObj, IntPtr_t ___imagePoints_nativeObj, double ___size_width, double ___size_height, IntPtr_t ___K_nativeObj, IntPtr_t ___xi_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___rvecs_mat_nativeObj, IntPtr_t ___tvecs_mat_nativeObj, int32_t ___flags, int32_t ___criteria_type, int32_t ___criteria_maxCount, double ___criteria_epsilon, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::ccalib_Ccalib_stereoCalibrate_10(System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.Double,System.Double,System.Double,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Double,System.IntPtr)
extern "C"  double Ccalib_ccalib_Ccalib_stereoCalibrate_10_m2763015875 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_mat_nativeObj, IntPtr_t ___imagePoints1_mat_nativeObj, IntPtr_t ___imagePoints2_mat_nativeObj, double ___imageSize1_width, double ___imageSize1_height, double ___imageSize2_width, double ___imageSize2_height, IntPtr_t ___K1_nativeObj, IntPtr_t ___xi1_nativeObj, IntPtr_t ___D1_nativeObj, IntPtr_t ___K2_nativeObj, IntPtr_t ___xi2_nativeObj, IntPtr_t ___D2_nativeObj, IntPtr_t ___rvec_nativeObj, IntPtr_t ___tvec_nativeObj, IntPtr_t ___rvecsL_mat_nativeObj, IntPtr_t ___tvecsL_mat_nativeObj, int32_t ___flags, int32_t ___criteria_type, int32_t ___criteria_maxCount, double ___criteria_epsilon, IntPtr_t ___idx_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Double OpenCVForUnity.Ccalib::ccalib_Ccalib_stereoCalibrate_11(System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.Double,System.Double,System.Double,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Double)
extern "C"  double Ccalib_ccalib_Ccalib_stereoCalibrate_11_m2717277558 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_mat_nativeObj, IntPtr_t ___imagePoints1_mat_nativeObj, IntPtr_t ___imagePoints2_mat_nativeObj, double ___imageSize1_width, double ___imageSize1_height, double ___imageSize2_width, double ___imageSize2_height, IntPtr_t ___K1_nativeObj, IntPtr_t ___xi1_nativeObj, IntPtr_t ___D1_nativeObj, IntPtr_t ___K2_nativeObj, IntPtr_t ___xi2_nativeObj, IntPtr_t ___D2_nativeObj, IntPtr_t ___rvec_nativeObj, IntPtr_t ___tvec_nativeObj, IntPtr_t ___rvecsL_mat_nativeObj, IntPtr_t ___tvecsL_mat_nativeObj, int32_t ___flags, int32_t ___criteria_type, int32_t ___criteria_maxCount, double ___criteria_epsilon, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_initUndistortRectifyMap_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.Double,System.Int32,System.IntPtr,System.IntPtr,System.Int32)
extern "C"  void Ccalib_ccalib_Ccalib_initUndistortRectifyMap_10_m2683003566 (Il2CppObject * __this /* static, unused */, IntPtr_t ___K_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___xi_nativeObj, IntPtr_t ___R_nativeObj, IntPtr_t ___P_nativeObj, double ___size_width, double ___size_height, int32_t ___mltype, IntPtr_t ___map1_nativeObj, IntPtr_t ___map2_nativeObj, int32_t ___flags, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_projectPoints_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.IntPtr,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_projectPoints_10_m3550639936 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_mat_nativeObj, IntPtr_t ___imagePoints_mat_nativeObj, IntPtr_t ___rvec_nativeObj, IntPtr_t ___tvec_nativeObj, IntPtr_t ___K_nativeObj, double ___xi, IntPtr_t ___D_nativeObj, IntPtr_t ___jacobian_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_projectPoints_11(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_projectPoints_11_m3365505425 (Il2CppObject * __this /* static, unused */, IntPtr_t ___objectPoints_mat_nativeObj, IntPtr_t ___imagePoints_mat_nativeObj, IntPtr_t ___rvec_nativeObj, IntPtr_t ___tvec_nativeObj, IntPtr_t ___K_nativeObj, double ___xi, IntPtr_t ___D_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_stereoReconstruct_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.IntPtr,System.IntPtr,System.IntPtr,System.Double,System.Double,System.IntPtr,System.IntPtr,System.Int32)
extern "C"  void Ccalib_ccalib_Ccalib_stereoReconstruct_10_m2227435264 (Il2CppObject * __this /* static, unused */, IntPtr_t ___image1_nativeObj, IntPtr_t ___image2_nativeObj, IntPtr_t ___K1_nativeObj, IntPtr_t ___D1_nativeObj, IntPtr_t ___xi1_nativeObj, IntPtr_t ___K2_nativeObj, IntPtr_t ___D2_nativeObj, IntPtr_t ___xi2_nativeObj, IntPtr_t ___R_nativeObj, IntPtr_t ___T_nativeObj, int32_t ___flag, int32_t ___numDisparities, int32_t ___SADWindowSize, IntPtr_t ___disparity_nativeObj, IntPtr_t ___image1Rec_nativeObj, IntPtr_t ___image2Rec_nativeObj, double ___newSize_width, double ___newSize_height, IntPtr_t ___Knew_nativeObj, IntPtr_t ___pointCloud_nativeObj, int32_t ___pointType, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_stereoReconstruct_11(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.IntPtr,System.IntPtr,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_stereoReconstruct_11_m110585316 (Il2CppObject * __this /* static, unused */, IntPtr_t ___image1_nativeObj, IntPtr_t ___image2_nativeObj, IntPtr_t ___K1_nativeObj, IntPtr_t ___D1_nativeObj, IntPtr_t ___xi1_nativeObj, IntPtr_t ___K2_nativeObj, IntPtr_t ___D2_nativeObj, IntPtr_t ___xi2_nativeObj, IntPtr_t ___R_nativeObj, IntPtr_t ___T_nativeObj, int32_t ___flag, int32_t ___numDisparities, int32_t ___SADWindowSize, IntPtr_t ___disparity_nativeObj, IntPtr_t ___image1Rec_nativeObj, IntPtr_t ___image2Rec_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_stereoRectify_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_stereoRectify_10_m1181959230 (Il2CppObject * __this /* static, unused */, IntPtr_t ___R_nativeObj, IntPtr_t ___T_nativeObj, IntPtr_t ___R1_nativeObj, IntPtr_t ___R2_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_undistortImage_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32,System.IntPtr,System.Double,System.Double,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_undistortImage_10_m213309428 (Il2CppObject * __this /* static, unused */, IntPtr_t ___distorted_nativeObj, IntPtr_t ___undistorted_nativeObj, IntPtr_t ___K_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___xi_nativeObj, int32_t ___flags, IntPtr_t ___Knew_nativeObj, double ___new_size_width, double ___new_size_height, IntPtr_t ___R_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_undistortImage_11(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32)
extern "C"  void Ccalib_ccalib_Ccalib_undistortImage_11_m416624097 (Il2CppObject * __this /* static, unused */, IntPtr_t ___distorted_nativeObj, IntPtr_t ___undistorted_nativeObj, IntPtr_t ___K_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___xi_nativeObj, int32_t ___flags, const MethodInfo* method) IL2CPP_METHOD_ATTR;
// System.Void OpenCVForUnity.Ccalib::ccalib_Ccalib_undistortPoints_10(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)
extern "C"  void Ccalib_ccalib_Ccalib_undistortPoints_10_m73979375 (Il2CppObject * __this /* static, unused */, IntPtr_t ___distorted_nativeObj, IntPtr_t ___undistorted_nativeObj, IntPtr_t ___K_nativeObj, IntPtr_t ___D_nativeObj, IntPtr_t ___xi_nativeObj, IntPtr_t ___R_nativeObj, const MethodInfo* method) IL2CPP_METHOD_ATTR;
